# Utility functions for streaming videos using mediapipe cv2 and graph matching and 
# other bunch of utility functions like (counting some pose, correctness etc) 

import cv2 
import math 
import json 
import numpy as np
import mediapipe as mp 
import matplotlib.pyplot as plt 

from fastdtw import fastdtw
from scipy.spatial import procrustes
from scipy.spatial.distance import euclidean

from typing import List, Tuple, Optional 

# mediapipe libraries
from mediapipe.python.solution_base import SolutionOutputs

class Draw:
    """
    Mediapipe is limited when it comes to drawing pose landmarks. Pose landmarks generated by mediapipe 
    is wrapped by a specific class type. But suppose our landmarks is a json object or a numpy array. What we
    gonna do in that case. The class Draw helps to deal with that.
    """
    def __init__(self) -> None:
        ... 
    
    def draw_mediapipe_pose(self, image : np.ndarray, results : SolutionOutputs) -> np.ndarray:
        ... 
    
    def convert_pose_landmark_to_list(self, pose_results : SolutionOutputs) -> List[List[float]]:
        ... 
    
